name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: '5.0.x'
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MultiFunPlayer-${{ steps.gitversion.outputs.fullSemVer }}.Branch.${{ steps.gitversion.outputs.escapedBranchName }}
        path: MultiFunPlayer\bin\Debug
